# see https://github.com/pages-themes/slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: {{ page.title }}
description: <a href="/">Fieldgauge</a>'s Adventures In Technology
